### ISSUE TITLE
bug: TypeScript import names are the same color as the import keyword

### ISSUE THREAD

**Issue by jackfranklin** [uncleTen276/dark_flat.nvim#1]
### Describe the bug

```
import * as X from 'y.js'
```

Note (see screenshot) that the colour of the actual import is the same as the other keywords, and means it is hard to differentiate. Ideally it would be marked in a different color.

<img width="712" alt="Screenshot 2023-07-20 at 14 40 42" src="https://github.com/sekke276/dark_flat.nvim/assets/193238/7462aa50-eb72-4d24-bce9-a6680dff39a3">

<img width="603" alt="Screenshot 2023-07-20 at 14 41 42" src="https://github.com/sekke276/dark_flat.nvim/assets/193238/ac0d5996-ed40-4014-a160-16a42afea7fe">

### Operating System + version

13.4.1 Mac OSX

### Neovim version

NVIM v0.10.0-dev-433+g4b60267f8

### Reproduce steps

1. Load up a TypeScript project with LSP configured
2. Find a file that has an ES Module import in

**Comment by jackfranklin** [comment]
<img width="679" alt="Screenshot 2023-07-20 at 14 49 48" src="https://github.com/sekke276/dark_flat.nvim/assets/193238/3b1d826f-d906-4952-94ee-632d1aff3f6c">

```
require("dark_flat").setup({
  themes = function(colors)
    return {
      ["@include.typescript"] = { fg = colors.white:darken(0.8) },
    }
  end,
})
```

Makes this look much nicer. I would be happy to contribute this back if you are happy with this?

**Comment by uncleTen276** [comment]
I have solved. Pls try to sync again 🤔

**Comment by jackfranklin** [comment]
Thanks!
